/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./components/layout/Aside.vue')['default']
    AudioPlayer: typeof import('./components/audioPlayer/AudioPlayer.vue')['default']
    BarTools: typeof import('./components/layout/BarTools.vue')['default']
    Breadcrumb: typeof import('./components/layout/Breadcrumb.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Layout: typeof import('./components/layout/Layout.vue')['default']
    Result: typeof import('./components/result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCol: typeof import('tdesign-vue-next')['Col']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
